# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='number_text',
            field=models.CharField(default='102', max_length=200),
            preserve_default=False,
        ),
    ]
